In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Delhi_v2.csv')

In [3]:
data.head

<bound method NDFrame.head of       Unnamed: 0       price  \
0              0   5600000.0
1              1   8800000.0
2              2  16500000.0
3              3   3810000.0
4              4   6200000.0
...          ...         ...
7733        7733   7900000.0
7734        7734   4510000.0
7735        7735   7000000.0
7736        7736   6500000.0
7737        7737   6500000.0

                                                Address    area   latitude  \
0                     Noida Extension, Noida, Delhi NCR  1350.0  28.608850
1                         Sector 79, Gurgaon, Delhi NCR  1490.0  28.374236
2                        Vaishali, Ghaziabad, Delhi NCR  2385.0  28.645769
3     Link Road, F Block, Sector 50, Noida, Uttar Pr...  1050.0  28.566914
4     Jaypee Pavilion Court Sector 128, Noida, Secto...  1350.0  28.520732
...                                                 ...     ...        ...
7733                  Indirapuram, Ghaziabad, Delhi NCR  1095.0  28.635272
7734  Greater Noida, Sector 2, Greater Noida, Delhi NCR  1060.0  28.581431
7735           Crossings Republik, Ghaziabad, Delhi NCR  1898.0  28.625850
7736  Raj Nagar Extension, Ghaziabad, Raj Nagar Exte...  1400.0  28.701622
7737  sandal apartment, Shalimar Garden Extension 1,...  1750.0  28.693590

      longitude  Bedrooms  Bathrooms  Balcony              Status  \
0     77.460560       3.0        3.0      NaN  Under Construction
1     76.952416       3.0        3.0      NaN       Ready to Move
2     77.385110       4.0        5.0      NaN       Ready to Move
3     77.436434       2.0        2.0      3.0                 NaN
4     77.356491       2.0        2.0      3.0       Ready to Move
...         ...       ...        ...      ...                 ...
7733  77.370395       2.0        2.0      NaN       Ready to Move
7734  77.452819       2.0        2.0      3.0                 NaN
7735  77.435336       4.0        3.0      5.0       Ready to Move
7736  77.430153       3.0        3.0      2.0       Ready to Move
7737  77.344376       3.0        2.0      3.0       Ready to Move

          neworold  parking Furnished_status  Lift  \
0     New Property      NaN              NaN   2.0
1     New Property      NaN   Semi-Furnished   2.0
2     New Property      1.0      Unfurnished   NaN
3     New Property      1.0      Unfurnished   2.0
4           Resale      1.0              NaN   3.0
...            ...      ...              ...   ...
7733        Resale      NaN              NaN   NaN
7734        Resale      NaN   Semi-Furnished   NaN
7735        Resale      NaN              NaN   NaN
7736        Resale      1.0              NaN   3.0
7737  New Property      NaN              NaN   NaN

                       Landmarks type_of_building  \
0                            NaN             Flat
1                            NaN             Flat
2                            NaN             Flat
3     near Gaur Mulberry Mansion             Flat
4                            NaN             Flat
...                          ...              ...
7733                         NaN             Flat
7734              ek murti chowk             Flat
7735                         NaN             Flat
7736                   vvip mall             Flat
7737                         NaN             Flat

                                                   desc   Price_sqft
0     \n\n\n                                Welcome ...  4148.148148
1     \n\n\n                                Mapsko M...  5906.040268
2     \n\n\n                                This pro...  6918.238994
3     \n\n\n                                AIG Roya...  3628.571429
4     \n\n\n                                The prop...  4592.592593
...                                                 ...          ...
7733  \n                    \n                    \n...  7214.611872
7734  \n                    \n                    \n...  4254.716981
7735  \n                    \n                    \n...  3688.092729
7736  \n                    \n                    \n...  4642.857143
7737                                                 \n  3714.285714

[7738 rows x 18 columns]>

In [4]:
data.shape

(7738, 18)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7738 entries, 0 to 7737
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        7738 non-null   int64
 1   price             7738 non-null   float64
 2   Address           7738 non-null   object
 3   area              7738 non-null   float64
 4   latitude          7738 non-null   float64
 5   longitude         7738 non-null   float64
 6   Bedrooms          7738 non-null   float64
 7   Bathrooms         7738 non-null   float64
 8   Balcony           5166 non-null   float64
 9   Status            7164 non-null   object
 10  neworold          7738 non-null   object
 11  parking           2612 non-null   float64
 12  Furnished_status  4124 non-null   object
 13  Lift              1733 non-null   float64
 14  Landmarks         2759 non-null   object
 15  type_of_building  7738 non-null   object
 16  desc              7738 non-null   object
 17  Price_sqft        7738 non-null   float64
dtypes: float64(10), int64(1), object(7)
memory usage: 1.1+ MB

In [6]:
for column in data.columns:
    print(data[column].value_counts())
    print("*"*20)

Unnamed: 0
0       1
5198    1
5166    1
5165    1
5164    1
       ..
2575    1
2574    1
2573    1
2572    1
7737    1
Name: count, Length: 7738, dtype: int64
********************
price
4500000.0    290
3500000.0    252
4000000.0    247
6000000.0    243
5500000.0    223
            ...
6860000.0      1
5290000.0      1
8450000.0      1
7670000.0      1
4510000.0      1
Name: count, Length: 584, dtype: int64
********************
Address
Raj Nagar Extension, Ghaziabad, Delhi NCR                                     163
Indirapuram, Ghaziabad, Delhi NCR                                             152
Greater Noida West, Greater Noida, Delhi NCR                                  100
Noida Extension, Noida, Delhi NCR                                              63
NH 24, Ghaziabad, Delhi NCR                                                    61
                                                                             ...
e block sector 57, Sector 57, Gurgaon, Delhi NCR                                1
Ramakrishna apartment, Indraprastha Extension, New Delhi - East, Delhi NCR      1
Rajnagar Extension Gahziabad, Raj Nagar Extension, Ghaziabad, Delhi NCR         1
Rajendra Park, Rajendra Park, Gurgaon, Delhi NCR                                1
sandal apartment, Shalimar Garden Extension 1, Ghaziabad, Delhi NCR             1
Name: count, Length: 4145, dtype: int64
********************
area
900.0     325
1000.0    264
1100.0    205
1200.0    156
800.0     137
         ...
1067.0      1
1638.0      1
1531.0      1
4690.0      1
1898.0      1
Name: count, Length: 1102, dtype: int64
********************
latitude
28.605958    101
28.649348     79
28.704053     62
28.646286     37
28.664488     30
            ...
28.507627      1
28.491388      1
28.586720      1
28.598970      1
28.625850      1
Name: count, Length: 2942, dtype: int64
********************
longitude
77.444512    101
77.369626     79
77.437331     62
77.406051     37
77.347494     30
            ...
77.261925      1
77.409897      1
77.336327      1
77.433517      1
77.435336      1
Name: count, Length: 2912, dtype: int64
********************
Bedrooms
2.0     3525
3.0     3373
4.0      642
5.0       98
6.0       46
7.0       17
9.0       16
10.0      11
8.0       10
Name: count, dtype: int64
********************
Bathrooms
2.0     5051
3.0     1907
4.0      551
5.0      138
6.0       44
7.0       21
8.0       12
9.0       10
10.0       4
Name: count, dtype: int64
********************
Balcony
2.0     1793
3.0     1516
1.0     1082
4.0      613
5.0      130
6.0       21
7.0        4
10.0       3
8.0        3
9.0        1
Name: count, dtype: int64
********************
Status
Ready to Move         7148
Under Construction      16
Name: count, dtype: int64
********************
neworold
Resale          6905
New Property     833
Name: count, dtype: int64
********************
parking
1.0      1715
2.0       640
3.0       110
4.0        45
6.0        14
         ...
18.0        1
602.0       1
16.0        1
624.0       1
179.0       1
Name: count, Length: 65, dtype: int64
********************
Furnished_status
Semi-Furnished    2199
Unfurnished       1230
Furnished          695
Name: count, dtype: int64
********************
Lift
2.0     800
1.0     296
0.0     269
3.0     258
4.0      86
6.0       8
5.0       7
7.0       4
10.0      2
8.0       2
9.0       1
Name: count, dtype: int64
********************
Landmarks
metro station                                    8
NH 8 and Dwarka Expressway                       6
Shipra Mall                                      6
DPS School                                       6
abes engineering college                         5
                                                ..
Next to sector 78 metro station                  1
Main Market is just 100 mtr walking distance.    1
telephone exchange sector 12, gurgaon            1
Nearby Sanjay Park                               1
vvip mall                                        1
Name: count, Length: 2612, dtype: int64
********************
type_of_building
Flat                6226
Individual House    1512
Name: count, dtype: int64
********************
desc
\n                                                                                                                                                                                                                                                                                                                                                                                 3257
\n                    \n                    \n                    \n                       Multistorey apartment is available for sale. It is a good location property. Please contact for more details.\n                    \n                                                                                                                                                    145
\n                    \n                    \n                    \n                       property is in a good locality\n                    \n                                                                                                                                                                                                                                    25
\n                    \n                    \n                    \n                       Builder floor apartment is available for sale. It is a good location property. Please contact for more details.\n                    \n                                                                                                                                                   21
\n                    \n                    \n                    \n                       Multistorey apartment is available for sale.it is a good location property. Please contact for more details.\n                    \n                                                                                                                                                      20
                                                                                                                                                                                                                                                                                                                                                                                   ...
\n                    \n                    \n                    \n                       3rd floor with roof right without lift and parking.\n                    \n                                                                                                                                                                                                                1
\n                    \n                    \n                    \n                       excellent ventilation,  fans ND Havells geysers provided  , furnished kitchen ND wardrobes made up of brand hetich\n                    \n                                                                                                                                                 1
\n                    \n                    \n                    \n                       Multistorey apartment is available for sale. It has covered area 602 sq-ft, it is 2 BHK apartment. Please contact for more details.\n                    \n                                                                                                                                1
\n                    \n                    \n                    \n                        It's a 2nd floor Builder Floor Apartment in a building of total 3 floors. The location has easy access to, Oriental Bank of Commerce (1 km ), Delhi College of Studies (1 km ), Parsvanath MMX (2 km ) and Vaishali Metro Station (4 km ). \n                    \n                       1
\n                    \n                    \n                    \n                       vvip flat available for sale 3bhk unit below 10th floor\n                    \n                                                                                                                                                                                                            1
Name: count, Length: 4181, dtype: int64
********************
Price_sqft
5000.000000     125
4000.000000      83
5555.555556      53
3333.333333      52
10000.000000     52
               ...
5391.304348       1
3952.901598       1
3900.975244       1
3361.344538       1
3688.092729       1
Name: count, Length: 3946, dtype: int64
********************

In [7]:
data.isna().sum()

Unnamed: 0             0
price                  0
Address                0
area                   0
latitude               0
longitude              0
Bedrooms               0
Bathrooms              0
Balcony             2572
Status               574
neworold               0
parking             5126
Furnished_status    3614
Lift                6005
Landmarks           4979
type_of_building       0
desc                   0
Price_sqft             0
dtype: int64

In [8]:
data.drop(columns=['Lift', 'parking', 'Landmarks', 'Balcony'], inplace=True)

In [9]:
data.describe()

,Unnamed: 0,price,area,latitude,longitude,Bedrooms,Bathrooms,Price_sqft
count,7738.000000,7.738000e+03,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000
mean,3868.500000,8.320635e+06,1409.506591,28.552092,77.273476,2.708193,2.501163,5543.660241
std,2233.912524,7.223197e+06,718.929581,0.107420,0.180606,0.877026,0.867050,2408.659307
min,0.000000,1.700000e+06,501.000000,28.240023,76.884101,2.000000,2.000000,2100.000000
25%,1934.250000,4.200000e+06,990.000000,28.455539,77.078590,2.000000,2.000000,3950.986915
50%,3868.500000,6.000000e+06,1250.000000,28.574637,77.345320,3.000000,2.000000,4972.674332
75%,5802.750000,9.500000e+06,1650.000000,28.642520,77.421054,3.000000,3.000000,6350.638693
max,7737.000000,8.500000e+07,9500.000000,28.799748,77.688028,10.000000,10.000000,44378.698225

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7738 entries, 0 to 7737
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        7738 non-null   int64
 1   price             7738 non-null   float64
 2   Address           7738 non-null   object
 3   area              7738 non-null   float64
 4   latitude          7738 non-null   float64
 5   longitude         7738 non-null   float64
 6   Bedrooms          7738 non-null   float64
 7   Bathrooms         7738 non-null   float64
 8   Status            7164 non-null   object
 9   neworold          7738 non-null   object
 10  Furnished_status  4124 non-null   object
 11  type_of_building  7738 non-null   object
 12  desc              7738 non-null   object
 13  Price_sqft        7738 non-null   float64
dtypes: float64(7), int64(1), object(6)
memory usage: 846.5+ KB

In [11]:
data['Status'] = data['Status'].fillna('Ready to Move')

In [12]:
data['Furnished_status'] = data['Furnished_status'].fillna('Unfurnished')

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7738 entries, 0 to 7737
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        7738 non-null   int64
 1   price             7738 non-null   float64
 2   Address           7738 non-null   object
 3   area              7738 non-null   float64
 4   latitude          7738 non-null   float64
 5   longitude         7738 non-null   float64
 6   Bedrooms          7738 non-null   float64
 7   Bathrooms         7738 non-null   float64
 8   Status            7738 non-null   object
 9   neworold          7738 non-null   object
 10  Furnished_status  7738 non-null   object
 11  type_of_building  7738 non-null   object
 12  desc              7738 non-null   object
 13  Price_sqft        7738 non-null   float64
dtypes: float64(7), int64(1), object(6)
memory usage: 846.5+ KB

In [14]:
for column in data.columns:
    print(data[column].value_counts())
    print("*"*20)

Unnamed: 0
0       1
5198    1
5166    1
5165    1
5164    1
       ..
2575    1
2574    1
2573    1
2572    1
7737    1
Name: count, Length: 7738, dtype: int64
********************
price
4500000.0    290
3500000.0    252
4000000.0    247
6000000.0    243
5500000.0    223
            ...
6860000.0      1
5290000.0      1
8450000.0      1
7670000.0      1
4510000.0      1
Name: count, Length: 584, dtype: int64
********************
Address
Raj Nagar Extension, Ghaziabad, Delhi NCR                                     163
Indirapuram, Ghaziabad, Delhi NCR                                             152
Greater Noida West, Greater Noida, Delhi NCR                                  100
Noida Extension, Noida, Delhi NCR                                              63
NH 24, Ghaziabad, Delhi NCR                                                    61
                                                                             ...
e block sector 57, Sector 57, Gurgaon, Delhi NCR                                1
Ramakrishna apartment, Indraprastha Extension, New Delhi - East, Delhi NCR      1
Rajnagar Extension Gahziabad, Raj Nagar Extension, Ghaziabad, Delhi NCR         1
Rajendra Park, Rajendra Park, Gurgaon, Delhi NCR                                1
sandal apartment, Shalimar Garden Extension 1, Ghaziabad, Delhi NCR             1
Name: count, Length: 4145, dtype: int64
********************
area
900.0     325
1000.0    264
1100.0    205
1200.0    156
800.0     137
         ...
1067.0      1
1638.0      1
1531.0      1
4690.0      1
1898.0      1
Name: count, Length: 1102, dtype: int64
********************
latitude
28.605958    101
28.649348     79
28.704053     62
28.646286     37
28.664488     30
            ...
28.507627      1
28.491388      1
28.586720      1
28.598970      1
28.625850      1
Name: count, Length: 2942, dtype: int64
********************
longitude
77.444512    101
77.369626     79
77.437331     62
77.406051     37
77.347494     30
            ...
77.261925      1
77.409897      1
77.336327      1
77.433517      1
77.435336      1
Name: count, Length: 2912, dtype: int64
********************
Bedrooms
2.0     3525
3.0     3373
4.0      642
5.0       98
6.0       46
7.0       17
9.0       16
10.0      11
8.0       10
Name: count, dtype: int64
********************
Bathrooms
2.0     5051
3.0     1907
4.0      551
5.0      138
6.0       44
7.0       21
8.0       12
9.0       10
10.0       4
Name: count, dtype: int64
********************
Status
Ready to Move         7722
Under Construction      16
Name: count, dtype: int64
********************
neworold
Resale          6905
New Property     833
Name: count, dtype: int64
********************
Furnished_status
Unfurnished       4844
Semi-Furnished    2199
Furnished          695
Name: count, dtype: int64
********************
type_of_building
Flat                6226
Individual House    1512
Name: count, dtype: int64
********************
desc
\n                                                                                                                                                                                                                                                                                                                                                                                 3257
\n                    \n                    \n                    \n                       Multistorey apartment is available for sale. It is a good location property. Please contact for more details.\n                    \n                                                                                                                                                    145
\n                    \n                    \n                    \n                       property is in a good locality\n                    \n                                                                                                                                                                                                                                    25
\n                    \n                    \n                    \n                       Builder floor apartment is available for sale. It is a good location property. Please contact for more details.\n                    \n                                                                                                                                                   21
\n                    \n                    \n                    \n                       Multistorey apartment is available for sale.it is a good location property. Please contact for more details.\n                    \n                                                                                                                                                      20
                                                                                                                                                                                                                                                                                                                                                                                   ...
\n                    \n                    \n                    \n                       3rd floor with roof right without lift and parking.\n                    \n                                                                                                                                                                                                                1
\n                    \n                    \n                    \n                       excellent ventilation,  fans ND Havells geysers provided  , furnished kitchen ND wardrobes made up of brand hetich\n                    \n                                                                                                                                                 1
\n                    \n                    \n                    \n                       Multistorey apartment is available for sale. It has covered area 602 sq-ft, it is 2 BHK apartment. Please contact for more details.\n                    \n                                                                                                                                1
\n                    \n                    \n                    \n                        It's a 2nd floor Builder Floor Apartment in a building of total 3 floors. The location has easy access to, Oriental Bank of Commerce (1 km ), Delhi College of Studies (1 km ), Parsvanath MMX (2 km ) and Vaishali Metro Station (4 km ). \n                    \n                       1
\n                    \n                    \n                    \n                       vvip flat available for sale 3bhk unit below 10th floor\n                    \n                                                                                                                                                                                                            1
Name: count, Length: 4181, dtype: int64
********************
Price_sqft
5000.000000     125
4000.000000      83
5555.555556      53
3333.333333      52
10000.000000     52
               ...
5391.304348       1
3952.901598       1
3900.975244       1
3361.344538       1
3688.092729       1
Name: count, Length: 3946, dtype: int64
********************

In [15]:
data['Address'].value_counts()

Address
Raj Nagar Extension, Ghaziabad, Delhi NCR                                     163
Indirapuram, Ghaziabad, Delhi NCR                                             152
Greater Noida West, Greater Noida, Delhi NCR                                  100
Noida Extension, Noida, Delhi NCR                                              63
NH 24, Ghaziabad, Delhi NCR                                                    61
                                                                             ...
e block sector 57, Sector 57, Gurgaon, Delhi NCR                                1
Ramakrishna apartment, Indraprastha Extension, New Delhi - East, Delhi NCR      1
Rajnagar Extension Gahziabad, Raj Nagar Extension, Ghaziabad, Delhi NCR         1
Rajendra Park, Rajendra Park, Gurgaon, Delhi NCR                                1
sandal apartment, Shalimar Garden Extension 1, Ghaziabad, Delhi NCR             1
Name: count, Length: 4145, dtype: int64

In [16]:
data['Address'] = data['Address'].apply(lambda x:x.strip())
address_count = data['Address'].value_counts()

In [17]:
address_count

Address
Raj Nagar Extension, Ghaziabad, Delhi NCR                                     163
Indirapuram, Ghaziabad, Delhi NCR                                             152
Greater Noida West, Greater Noida, Delhi NCR                                  100
Noida Extension, Noida, Delhi NCR                                              63
NH 24, Ghaziabad, Delhi NCR                                                    61
                                                                             ...
e block sector 57, Sector 57, Gurgaon, Delhi NCR                                1
Ramakrishna apartment, Indraprastha Extension, New Delhi - East, Delhi NCR      1
Rajnagar Extension Gahziabad, Raj Nagar Extension, Ghaziabad, Delhi NCR         1
Rajendra Park, Rajendra Park, Gurgaon, Delhi NCR                                1
sandal apartment, Shalimar Garden Extension 1, Ghaziabad, Delhi NCR             1
Name: count, Length: 4145, dtype: int64

In [18]:
address_count_less10 = address_count[address_count<=10]
address_count_less10

Address
Surajpur, Greater Noida, Delhi NCR                                            10
Sector 21C, Faridabad, Delhi NCR                                              10
Sector 107, Gurgaon, Delhi NCR                                                10
Sector 90, Gurgaon, Delhi NCR                                                 10
Sector 79, Noida, Delhi NCR                                                   10
                                                                              ..
e block sector 57, Sector 57, Gurgaon, Delhi NCR                               1
Ramakrishna apartment, Indraprastha Extension, New Delhi - East, Delhi NCR     1
Rajnagar Extension Gahziabad, Raj Nagar Extension, Ghaziabad, Delhi NCR        1
Rajendra Park, Rajendra Park, Gurgaon, Delhi NCR                               1
sandal apartment, Shalimar Garden Extension 1, Ghaziabad, Delhi NCR            1
Name: count, Length: 4056, dtype: int64

In [19]:
data['Address'] = data['Address'].apply(lambda x: 'other' if x in address_count_less10 else x)

In [20]:
data['Address'].value_counts()

Address
other                                           5621
Raj Nagar Extension, Ghaziabad, Delhi NCR        163
Indirapuram, Ghaziabad, Delhi NCR                152
Greater Noida West, Greater Noida, Delhi NCR     100
Noida Extension, Noida, Delhi NCR                 63
                                                ...
Sector 86, Faridabad, Delhi NCR                   11
Sector 86, Gurgaon, Delhi NCR                     11
Sector 70, Gurgaon, Delhi NCR                     11
Sector 119, Noida, Delhi NCR                      11
Sector 78, Faridabad, Delhi NCR                   11
Name: count, Length: 90, dtype: int64

In [21]:
data.describe()

,Unnamed: 0,price,area,latitude,longitude,Bedrooms,Bathrooms,Price_sqft
count,7738.000000,7.738000e+03,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000
mean,3868.500000,8.320635e+06,1409.506591,28.552092,77.273476,2.708193,2.501163,5543.660241
std,2233.912524,7.223197e+06,718.929581,0.107420,0.180606,0.877026,0.867050,2408.659307
min,0.000000,1.700000e+06,501.000000,28.240023,76.884101,2.000000,2.000000,2100.000000
25%,1934.250000,4.200000e+06,990.000000,28.455539,77.078590,2.000000,2.000000,3950.986915
50%,3868.500000,6.000000e+06,1250.000000,28.574637,77.345320,3.000000,2.000000,4972.674332
75%,5802.750000,9.500000e+06,1650.000000,28.642520,77.421054,3.000000,3.000000,6350.638693
max,7737.000000,8.500000e+07,9500.000000,28.799748,77.688028,10.000000,10.000000,44378.698225

In [22]:
data.shape

(7738, 14)

In [23]:
data.drop(columns=['Unnamed: 0', 'latitude', 'longitude'], inplace = True)

In [24]:
data

,price,Address,area,Bedrooms,Bathrooms,Status,neworold,Furnished_status,type_of_building,desc,Price_sqft
0,5600000.0,"Noida Extension, Noida, Delhi NCR",1350.0,3.0,3.0,Under Construction,New Property,Unfurnished,Flat,\n\n\n Welcome ...,4148.148148
1,8800000.0,"Sector 79, Gurgaon, Delhi NCR",1490.0,3.0,3.0,Ready to Move,New Property,Semi-Furnished,Flat,\n\n\n Mapsko M...,5906.040268
2,16500000.0,"Vaishali, Ghaziabad, Delhi NCR",2385.0,4.0,5.0,Ready to Move,New Property,Unfurnished,Flat,\n\n\n This pro...,6918.238994
3,3810000.0,other,1050.0,2.0,2.0,Ready to Move,New Property,Unfurnished,Flat,\n\n\n AIG Roya...,3628.571429
4,6200000.0,other,1350.0,2.0,2.0,Ready to Move,Resale,Unfurnished,Flat,\n\n\n The prop...,4592.592593
...,...,...,...,...,...,...,...,...,...,...,...
7733,7900000.0,"Indirapuram, Ghaziabad, Delhi NCR",1095.0,2.0,2.0,Ready to Move,Resale,Unfurnished,Flat,\n \n \n...,7214.611872
7734,4510000.0,other,1060.0,2.0,2.0,Ready to Move,Resale,Semi-Furnished,Flat,\n \n \n...,4254.716981
7735,7000000.0,"Crossings Republik, Ghaziabad, Delhi NCR",1898.0,4.0,3.0,Ready to Move,Resale,Unfurnished,Flat,\n \n \n...,3688.092729
7736,6500000.0,"Raj Nagar Extension, Ghaziabad, Raj Nagar Exte...",1400.0,3.0,3.0,Ready to Move,Resale,Unfurnished,Flat,\n \n \n...,4642.857143
7737,6500000.0,other,1750.0,3.0,2.0,Ready to Move,New Property,Unfurnished,Flat,\n,3714.285714

In [25]:
data.drop(columns=['type_of_building', 'desc', 'neworold'], inplace = True)

In [26]:
data

,price,Address,area,Bedrooms,Bathrooms,Status,Furnished_status,Price_sqft
0,5600000.0,"Noida Extension, Noida, Delhi NCR",1350.0,3.0,3.0,Under Construction,Unfurnished,4148.148148
1,8800000.0,"Sector 79, Gurgaon, Delhi NCR",1490.0,3.0,3.0,Ready to Move,Semi-Furnished,5906.040268
2,16500000.0,"Vaishali, Ghaziabad, Delhi NCR",2385.0,4.0,5.0,Ready to Move,Unfurnished,6918.238994
3,3810000.0,other,1050.0,2.0,2.0,Ready to Move,Unfurnished,3628.571429
4,6200000.0,other,1350.0,2.0,2.0,Ready to Move,Unfurnished,4592.592593
...,...,...,...,...,...,...,...,...
7733,7900000.0,"Indirapuram, Ghaziabad, Delhi NCR",1095.0,2.0,2.0,Ready to Move,Unfurnished,7214.611872
7734,4510000.0,other,1060.0,2.0,2.0,Ready to Move,Semi-Furnished,4254.716981
7735,7000000.0,"Crossings Republik, Ghaziabad, Delhi NCR",1898.0,4.0,3.0,Ready to Move,Unfurnished,3688.092729
7736,6500000.0,"Raj Nagar Extension, Ghaziabad, Raj Nagar Exte...",1400.0,3.0,3.0,Ready to Move,Unfurnished,4642.857143
7737,6500000.0,other,1750.0,3.0,2.0,Ready to Move,Unfurnished,3714.285714

## Cleaned Data

In [27]:
data.head()

,price,Address,area,Bedrooms,Bathrooms,Status,Furnished_status,Price_sqft
0,5600000.0,"Noida Extension, Noida, Delhi NCR",1350.0,3.0,3.0,Under Construction,Unfurnished,4148.148148
1,8800000.0,"Sector 79, Gurgaon, Delhi NCR",1490.0,3.0,3.0,Ready to Move,Semi-Furnished,5906.040268
2,16500000.0,"Vaishali, Ghaziabad, Delhi NCR",2385.0,4.0,5.0,Ready to Move,Unfurnished,6918.238994
3,3810000.0,other,1050.0,2.0,2.0,Ready to Move,Unfurnished,3628.571429
4,6200000.0,other,1350.0,2.0,2.0,Ready to Move,Unfurnished,4592.592593

In [28]:
data.to_csv('Cleaned.csv')

In [29]:
X = data.drop(columns =['price'])
y=data['price']

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [32]:
print(X_train.shape)
print(X_test.shape)

(6190, 7)
(1548, 7)

In [33]:
column_trans = make_column_transformer((OneHotEncoder(),['Address','Status','Furnished_status']),remainder = 'passthrough')

In [34]:
scaler = StandardScaler(with_mean=False)

In [35]:
lr = LinearRegression()

In [36]:
pipe = make_pipeline(column_trans,scaler,lr)

In [37]:
pipe.fit(X_train,y_train)
print(X_train.columns)

Index(['Address', 'area', 'Bedrooms', 'Bathrooms', 'Status',
       'Furnished_status', 'Price_sqft'],
      dtype='object')

In [38]:
print(X_train.dtypes)

Address              object
area                float64
Bedrooms            float64
Bathrooms           float64
Status               object
Furnished_status     object
Price_sqft          float64
dtype: object

In [39]:
y_pred_lr = pipe.predict(X_test)

In [40]:
r2_score(y_test, y_pred_lr)

0.9484960037085427

In [41]:
ridge = Ridge()

In [42]:
pipe = make_pipeline(column_trans,scaler,ridge)

In [43]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(),
                                                  ['Address', 'Status',
                                                   'Furnished_status'])])),
                ('standardscaler', StandardScaler(with_mean=False)),
                ('ridge', Ridge())])

In [44]:
y_pred_r = pipe.predict(X_test)

In [45]:
r2_score(y_test, y_pred_r)

0.9485054212481324

In [47]:
import tensorflow as tf
from joblib import  load

In [50]:
import pickle

In [51]:
pickle.dump(pipe, open('housing.pkl', 'wb'))

In [52]:
model = load('housing.pkl')

In [53]:
converter = tf.lite.TFLiteConverter.from_sklearn(model)
tflite_model = converter.convert()

AttributeError: type object 'TFLiteConverterV2' has no attribute 'from_sklearn'